# SPDX-License-Identifier: Apache-2.0
"""Property tests for RFC 8785 JCS canonical encoding stability (FR-4).

Complements ``test_structural_hash_jcs_stable.py`` (which pins the
sha256-of-JCS contract on the engine's structural-hash primitive) and
``test_ir_roundtrip.py`` (which pins Pydantic round-trip equality on
:class:`stargraph.ir.IRDocument`). This file pins the *raw JCS encoding* itself:

1. **Stable bytes across 100 random key orderings.** RFC 8785 lex-sorts
   object keys before serialization, so any IR-shaped dict re-built with
   shuffled key insertion order must canonicalize to the byte-identical
   output. Generated by Hypothesis from a recursive JSON-compatible
   strategy, then shuffled 100 times per example.

2. **Idempotence (canonical of canonical).** Parsing the canonical bytes
   back to a Python value and re-canonicalizing must yield the same bytes
   -- the FR-4 fixed-point property of the encoder.
"""

from __future__ import annotations

import json
import random
from typing import Any, cast

import rfc8785
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

# ---------------------------------------------------------------------------
# Hypothesis profile -- bounded examples; each example shuffles 100 times so
# per-example cost is non-trivial.
# ---------------------------------------------------------------------------

_PROFILE = settings(
    max_examples=50,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.data_too_large],
    deadline=None,
)


# ---------------------------------------------------------------------------
# IR-shaped JSON strategy: nested dicts/lists with JCS-safe scalars (no
# floats per FR-4; rfc8785 also forbids ints outside [-2**53, 2**53]).
# ---------------------------------------------------------------------------

_KEY = st.text(
    alphabet=st.characters(min_codepoint=0x21, max_codepoint=0x7E, blacklist_characters='"\\'),
    min_size=1,
    max_size=8,
)

_SCALAR = st.one_of(
    st.text(max_size=12),
    # rfc8785's safe integer domain is the open interval (-2**53, 2**53);
    # the boundary values themselves raise IntegerDomainError per RFC 8785 §6.
    st.integers(min_value=-(2**53) + 1, max_value=2**53 - 1),
    st.booleans(),
    st.none(),
)

_IR_LIKE: st.SearchStrategy[Any] = st.recursive(
    _SCALAR,
    lambda children: st.one_of(
        st.lists(children, max_size=4),
        st.dictionaries(_KEY, children, max_size=4),
    ),
    max_leaves=12,
)

_IR_DICT = st.dictionaries(_KEY, _IR_LIKE, min_size=1, max_size=6)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _shuffle_keys(value: Any, rng: random.Random) -> Any:
    """Return a structural copy of ``value`` with every dict's key order shuffled.

    Lists keep positional order (JCS is positional for arrays); only dict key
    insertion order is randomized so the test exercises rule (a) of RFC 8785
    -- lexicographic sort of object members.
    """
    if isinstance(value, dict):
        typed_value = cast("dict[str, Any]", value)
        items: list[tuple[str, Any]] = [(k, _shuffle_keys(v, rng)) for k, v in typed_value.items()]
        rng.shuffle(items)
        return dict(items)
    if isinstance(value, list):
        typed_list = cast("list[Any]", value)
        return [_shuffle_keys(item, rng) for item in typed_list]
    return value


# ---------------------------------------------------------------------------
# Property 1: insertion-order independence across 100 random key orderings.
# ---------------------------------------------------------------------------


@_PROFILE
@given(payload=_IR_DICT)
def test_jcs_stable_across_100_key_orderings(payload: dict[str, Any]) -> None:
    """RFC 8785 canonicalization yields byte-identical output across 100 key shuffles."""
    rng = random.Random(0xC0FFEE)
    encodings: set[bytes] = set()
    for _ in range(100):
        reordered = _shuffle_keys(payload, rng)
        encodings.add(rfc8785.dumps(reordered))
    assert len(encodings) == 1, (
        f"JCS encoding unstable across 100 key orderings: {len(encodings)} distinct"
    )


# ---------------------------------------------------------------------------
# Property 2: idempotence -- canonical(parse(canonical(x))) == canonical(x).
# ---------------------------------------------------------------------------


@_PROFILE
@given(payload=_IR_DICT)
def test_jcs_canonical_is_idempotent(payload: dict[str, Any]) -> None:
    """Canonical-of-canonical equals canonical (FR-4 fixed-point property)."""
    canonical = rfc8785.dumps(payload)
    reparsed = json.loads(canonical)
    assert rfc8785.dumps(reparsed) == canonical
