# SPDX-License-Identifier: Apache-2.0
"""Property tests for the JCS structural hash stability contract (FR-4).

Three contract guarantees, each pinned by Hypothesis:

1. **Insertion-order independence.** RFC 8785 (JSON Canonicalization Scheme)
   sorts object keys lexicographically before serialization, so the same
   semantic dict must produce an identical sha256 regardless of the order in
   which key/value pairs were inserted. Generated by shuffling 100 random
   orderings of a fixed set of (key, value) pairs.

2. **Float rejection.** The hash payload must NEVER contain a ``float`` field
   (RFC 8785 leaves IEEE-754 round-trip semantics unstable across runtimes;
   FR-4 forbids floats outright). Any input dict containing a float at any
   nesting depth must raise :class:`ValueError`.

3. **Topology lex-sort independence.** Per FR-4 normalization rule (a) —
   "node IDs sorted lexicographic, edges deduplicated and tuple-sorted by
   ``(src, dst, port)``" — an IR with shuffled ``nodes`` list must hash
   identically to the same IR with sorted nodes.

This test is the **TDD-RED** half of the FR-4 cycle. The
``harbor.graph.hash`` module does not yet exist; imports are deferred into
each test body so the file parses cleanly under ruff/pyright while the tests
themselves fail with :class:`ImportError` until task 1.9 lands the
implementation.
"""

from __future__ import annotations

import random
from typing import TYPE_CHECKING, Any, Protocol, cast

import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

if TYPE_CHECKING:
    from harbor.ir._models import IRDocument

    class _StructuralHash(Protocol):
        def __call__(self, payload: dict[str, Any]) -> str: ...


def _import_structural_hash() -> _StructuralHash:
    """Deferred import of the dict-in / hex-out primitive.

    Task 1.9 shipped the JCS+sha256 core under ``structural_hash``; task
    1.9.fix1 promoted that primitive to ``_structural_hash_dict`` (private)
    so the public ``structural_hash`` could take an IRDocument +
    rule_pack_versions per FR-4 amendment 3. The five property tests below
    were authored against the dict-shape contract (insertion-order /
    float-rejection / topology lex-sort) and continue to exercise the
    primitive directly — they remain the canonical pin on the JCS+sha256
    semantics that the IRDocument-shaped public API depends on.
    """
    import importlib

    module = importlib.import_module("harbor.graph.hash")
    return cast("_StructuralHash", module._structural_hash_dict)


# ---------------------------------------------------------------------------
# Hypothesis profile -- bounded examples; deferred imports inflate per-example
# cost slightly so we keep the count modest.
# ---------------------------------------------------------------------------

_PROFILE = settings(
    max_examples=50,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.data_too_large],
    deadline=None,
)


# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------

# JCS-safe scalars: NO floats (FR-4). Strings, ints, bools, None.
_JCS_SCALAR = st.one_of(
    st.text(max_size=16),
    st.integers(min_value=-(2**53), max_value=2**53),
    st.booleans(),
    st.none(),
)

_KEY = st.text(
    alphabet=st.characters(min_codepoint=0x21, max_codepoint=0x7E, blacklist_characters='"\\'),
    min_size=1,
    max_size=8,
)

# Flat dict with no floats; used to assert insertion-order independence.
_FLAT_DICT = st.dictionaries(_KEY, _JCS_SCALAR, min_size=1, max_size=8)

# Node-ID alphabet for topology shuffle test.
_NODE_ID = st.text(
    alphabet=st.characters(min_codepoint=0x41, max_codepoint=0x7A),
    min_size=1,
    max_size=6,
)


# ---------------------------------------------------------------------------
# Case 1: insertion-order independence (JCS lex-sorts keys).
# ---------------------------------------------------------------------------


@_PROFILE
@given(payload=_FLAT_DICT)
def test_structural_hash_insertion_order_independent(payload: dict[str, Any]) -> None:
    """Same canonical dict → identical sha256 across 100 random insertion orders."""
    structural_hash = _import_structural_hash()

    items = list(payload.items())
    rng = random.Random(0xC0FFEE)
    hashes: set[str] = set()
    for _ in range(100):
        rng.shuffle(items)
        reordered: dict[str, Any] = dict(items)
        hashes.add(structural_hash(reordered))
    # All 100 orderings must collapse to a single hash.
    assert len(hashes) == 1, f"unstable hash across orderings: {len(hashes)} distinct values"


# ---------------------------------------------------------------------------
# Case 2: float rejection (FR-4 forbids floats in hashed payload).
# ---------------------------------------------------------------------------


@_PROFILE
@given(
    key=_KEY,
    value=st.floats(allow_nan=False, allow_infinity=False, width=64),
)
def test_structural_hash_rejects_top_level_float(key: str, value: float) -> None:
    """A dict with a float field at the top level raises ``ValueError``."""
    structural_hash = _import_structural_hash()

    payload: dict[str, Any] = {key: value}
    with pytest.raises(ValueError, match=r"float"):
        structural_hash(payload)


@_PROFILE
@given(
    outer_key=_KEY,
    inner_key=_KEY,
    value=st.floats(allow_nan=False, allow_infinity=False, width=64),
)
def test_structural_hash_rejects_nested_float(outer_key: str, inner_key: str, value: float) -> None:
    """A dict with a float field nested inside a sub-dict raises ``ValueError``."""
    structural_hash = _import_structural_hash()

    payload: dict[str, Any] = {outer_key: {inner_key: value}}
    with pytest.raises(ValueError, match=r"float"):
        structural_hash(payload)


@_PROFILE
@given(
    key=_KEY,
    value=st.floats(allow_nan=False, allow_infinity=False, width=64),
)
def test_structural_hash_rejects_float_in_list(key: str, value: float) -> None:
    """A dict whose value is a list containing a float raises ``ValueError``."""
    structural_hash = _import_structural_hash()

    payload: dict[str, Any] = {key: [1, 2, value]}
    with pytest.raises(ValueError, match=r"float"):
        structural_hash(payload)


# ---------------------------------------------------------------------------
# Case 3: topology lex-sort independence (FR-4 normalization rule (a)).
# ---------------------------------------------------------------------------


@_PROFILE
@given(node_ids=st.lists(_NODE_ID, min_size=2, max_size=8, unique=True))
def test_structural_hash_topology_node_order_independent(node_ids: list[str]) -> None:
    """Topology with shuffled node IDs lex-sorts to identical hash."""
    structural_hash = _import_structural_hash()

    rng = random.Random(0xBEEF)
    hashes: set[str] = set()
    for _ in range(20):
        shuffled = list(node_ids)
        rng.shuffle(shuffled)
        topology: dict[str, Any] = {
            "topology": {
                "nodes": shuffled,
                "edges": [],
            }
        }
        hashes.add(structural_hash(topology))
    assert len(hashes) == 1, (
        f"topology hash unstable under node-list shuffle: {len(hashes)} distinct values"
    )


# ---------------------------------------------------------------------------
# IRDocument-shaped tests (FR-4 amendment 3, task 1.9.fix1).
#
# The public ``structural_hash`` takes an IRDocument + rule_pack_versions
# kwarg and computes the four-component canonical dict per FR-4 amendment 3:
# (a) topology, (b) node signatures, (c) state schema, (d) rule pack triples.
# These tests pin the three invariants the public surface guarantees:
#   - node insertion order does not change the hash (rule (a) lex-sort);
#   - rule_pack_versions list order does not change the hash (rule (d) sort);
#   - state-schema change DOES change the hash (rule (c) participation).
#
# Imports stay local so they don't fight the dict-primitive deferred-import
# pattern used by the five tests above.
# ---------------------------------------------------------------------------


def _build_ir(
    node_ids: list[str],
    state_schema: object | None = None,
) -> IRDocument:
    """Build a minimal IRDocument with the given node IDs (insertion order preserved).

    The optional ``state_schema`` lets a single test mutate just rule (c).
    """
    from harbor.ir._models import IRDocument, NodeSpec

    kwargs: dict[str, Any] = {
        "ir_version": "1.0.0",
        "id": "run:fix1",
        "nodes": [NodeSpec(id=nid, kind="task") for nid in node_ids],
    }
    if state_schema is not None:
        kwargs["state_schema"] = state_schema
    return IRDocument(**kwargs)


@pytest.mark.property
def test_irdocument_hash_stable() -> None:
    """Same IR built with two different node-insertion orders → identical hash.

    Amended per T18: mirrors Graph.__init__:384 — compile state_schema to a
    BaseModel subclass via _compile_state_schema and inject via model_copy
    before calling structural_hash (repr fallback removed by T18, FR-6).
    """
    from harbor.graph.definition import _compile_state_schema  # pyright: ignore[reportPrivateUsage]
    from harbor.graph.hash import structural_hash

    rule_packs: list[tuple[str, str, str]] = [("pack-a", "deadbeef", "1.0.0")]
    compiled = _compile_state_schema({}, graph_id="ir-test-stable")
    ir1_raw = _build_ir(["alpha", "beta", "gamma"])
    ir2_raw = _build_ir(["gamma", "alpha", "beta"])
    ir1 = ir1_raw.model_copy(update={"state_schema": compiled})  # type: ignore[arg-type]
    ir2 = ir2_raw.model_copy(update={"state_schema": compiled})  # type: ignore[arg-type]

    h1 = structural_hash(ir1, rule_pack_versions=rule_packs)
    h2 = structural_hash(ir2, rule_pack_versions=rule_packs)

    assert h1 == h2, "IRDocument hash must be invariant under node-insertion order"


@pytest.mark.property
def test_irdocument_rule_pack_order_invariant() -> None:
    """Same IR + same rule-pack triples in different orders → identical hash.

    Amended per T18: mirrors Graph.__init__:384 compile-then-replace pattern.
    """
    from harbor.graph.definition import _compile_state_schema  # pyright: ignore[reportPrivateUsage]
    from harbor.graph.hash import structural_hash

    compiled = _compile_state_schema({}, graph_id="ir-test-order")
    ir = _build_ir(["n1", "n2"]).model_copy(update={"state_schema": compiled})  # type: ignore[arg-type]
    packs_a: list[tuple[str, str, str]] = [
        ("pack-a", "aa11", "1.0.0"),
        ("pack-b", "bb22", "2.0.0"),
        ("pack-c", "cc33", "0.1.0"),
    ]
    packs_b: list[tuple[str, str, str]] = [
        ("pack-c", "cc33", "0.1.0"),
        ("pack-a", "aa11", "1.0.0"),
        ("pack-b", "bb22", "2.0.0"),
    ]

    h1 = structural_hash(ir, rule_pack_versions=packs_a)
    h2 = structural_hash(ir, rule_pack_versions=packs_b)

    assert h1 == h2, "structural_hash must be invariant under rule_pack_versions order"


@pytest.mark.property
def test_irdocument_state_schema_change_changes_hash() -> None:
    """Different state schema → different hash (rule (c) participates).

    Amended per T18: compile raw dicts via _compile_state_schema and inject
    via model_copy (mirrors Graph.__init__:384; repr fallback removed FR-6).
    """
    from harbor.graph.definition import _compile_state_schema  # pyright: ignore[reportPrivateUsage]
    from harbor.graph.hash import structural_hash

    rule_packs: list[tuple[str, str, str]] = [("pack-a", "deadbeef", "1.0.0")]
    schema1 = _compile_state_schema({"counter": "int"}, graph_id="ir-test-1")
    schema2 = _compile_state_schema({"counter": "str"}, graph_id="ir-test-2")
    ir1 = _build_ir(["n1"]).model_copy(update={"state_schema": schema1})  # type: ignore[arg-type]
    ir2 = _build_ir(["n1"]).model_copy(update={"state_schema": schema2})  # type: ignore[arg-type]

    h1 = structural_hash(ir1, rule_pack_versions=rule_packs)
    h2 = structural_hash(ir2, rule_pack_versions=rule_packs)

    assert h1 != h2, "structural_hash must change when state_schema changes"
