"""
Install map for 100 CVEs in the v2 scoring set.

Each entry describes how to install the *vulnerable* version of a package,
probe its version, and replace it with the *fixed* version — used by the
recipe generator to build per-CVE sandbox playbooks.
"""

_INSTALL_MAP: dict[str, dict] = {
    # ─────────────────────────────────────────────────────────────────────
    # MAVEN JAR  (install_type=maven_jar, install_channel=jar)
    # ─────────────────────────────────────────────────────────────────────
    "CVE-2021-44228": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "log4j-core",
        "vulnerable_version": "2.14.1",
        "fixed_version": "2.17.0",
        "maven_coord": "org.apache.logging.log4j:log4j-core",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/log4j-core-2.14.1.jar 'https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar'",
        "probe_cmd": "ls /opt/jars/log4j-core-2.14.1.jar >/dev/null 2>&1 && echo 'Version: 2.14.1'",
        "fix_cmd": "rm -f /opt/jars/log4j-core-2.14.1.jar && wget -qO /opt/jars/log4j-core-2.17.0.jar 'https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.17.0/log4j-core-2.17.0.jar'",
    },
    "CVE-2021-45046": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "log4j-core",
        "vulnerable_version": "2.15.0",
        "fixed_version": "2.17.0",
        "maven_coord": "org.apache.logging.log4j:log4j-core",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/log4j-core-2.15.0.jar 'https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.15.0/log4j-core-2.15.0.jar'",
        "probe_cmd": "ls /opt/jars/log4j-core-2.15.0.jar >/dev/null 2>&1 && echo 'Version: 2.15.0'",
        "fix_cmd": "rm -f /opt/jars/log4j-core-2.15.0.jar && wget -qO /opt/jars/log4j-core-2.17.0.jar 'https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.17.0/log4j-core-2.17.0.jar'",
    },
    "CVE-2017-5638": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "struts2-core",
        "vulnerable_version": "2.3.31",
        "fixed_version": "2.3.32",
        "maven_coord": "org.apache.struts:struts2-core",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/struts2-core-2.3.31.jar 'https://repo1.maven.org/maven2/org/apache/struts/struts2-core/2.3.31/struts2-core-2.3.31.jar'",
        "probe_cmd": "ls /opt/jars/struts2-core-2.3.31.jar >/dev/null 2>&1 && echo 'Version: 2.3.31'",
        "fix_cmd": "rm -f /opt/jars/struts2-core-2.3.31.jar && wget -qO /opt/jars/struts2-core-2.3.32.jar 'https://repo1.maven.org/maven2/org/apache/struts/struts2-core/2.3.32/struts2-core-2.3.32.jar'",
    },
    "CVE-2018-11776": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "struts2-core",
        "vulnerable_version": "2.3.34",
        "fixed_version": "2.3.35",
        "maven_coord": "org.apache.struts:struts2-core",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/struts2-core-2.3.34.jar 'https://repo1.maven.org/maven2/org/apache/struts/struts2-core/2.3.34/struts2-core-2.3.34.jar'",
        "probe_cmd": "ls /opt/jars/struts2-core-2.3.34.jar >/dev/null 2>&1 && echo 'Version: 2.3.34'",
        "fix_cmd": "rm -f /opt/jars/struts2-core-2.3.34.jar && wget -qO /opt/jars/struts2-core-2.3.35.jar 'https://repo1.maven.org/maven2/org/apache/struts/struts2-core/2.3.35/struts2-core-2.3.35.jar'",
    },
    "CVE-2022-22965": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "spring-beans",
        "vulnerable_version": "5.3.17",
        "fixed_version": "5.3.18",
        "maven_coord": "org.springframework:spring-beans",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/spring-beans-5.3.17.jar 'https://repo1.maven.org/maven2/org/springframework/spring-beans/5.3.17/spring-beans-5.3.17.jar'",
        "probe_cmd": "ls /opt/jars/spring-beans-5.3.17.jar >/dev/null 2>&1 && echo 'Version: 5.3.17'",
        "fix_cmd": "rm -f /opt/jars/spring-beans-5.3.17.jar && wget -qO /opt/jars/spring-beans-5.3.18.jar 'https://repo1.maven.org/maven2/org/springframework/spring-beans/5.3.18/spring-beans-5.3.18.jar'",
    },
    "CVE-2022-22963": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "spring-cloud-function-context",
        "vulnerable_version": "3.2.2",
        "fixed_version": "3.2.3",
        "maven_coord": "org.springframework.cloud:spring-cloud-function-context",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/spring-cloud-function-context-3.2.2.jar 'https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-function-context/3.2.2/spring-cloud-function-context-3.2.2.jar'",
        "probe_cmd": "ls /opt/jars/spring-cloud-function-context-3.2.2.jar >/dev/null 2>&1 && echo 'Version: 3.2.2'",
        "fix_cmd": "rm -f /opt/jars/spring-cloud-function-context-3.2.2.jar && wget -qO /opt/jars/spring-cloud-function-context-3.2.3.jar 'https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-function-context/3.2.3/spring-cloud-function-context-3.2.3.jar'",
    },
    "CVE-2022-22947": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "spring-cloud-gateway-server",
        "vulnerable_version": "3.1.0",
        "fixed_version": "3.1.1",
        "maven_coord": "org.springframework.cloud:spring-cloud-gateway-server",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/spring-cloud-gateway-server-3.1.0.jar 'https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-gateway-server/3.1.0/spring-cloud-gateway-server-3.1.0.jar'",
        "probe_cmd": "ls /opt/jars/spring-cloud-gateway-server-3.1.0.jar >/dev/null 2>&1 && echo 'Version: 3.1.0'",
        "fix_cmd": "rm -f /opt/jars/spring-cloud-gateway-server-3.1.0.jar && wget -qO /opt/jars/spring-cloud-gateway-server-3.1.1.jar 'https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-gateway-server/3.1.1/spring-cloud-gateway-server-3.1.1.jar'",
    },
    "CVE-2017-7525": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "jackson-databind",
        "vulnerable_version": "2.8.8",
        "fixed_version": "2.8.11.1",
        "maven_coord": "com.fasterxml.jackson.core:jackson-databind",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/jackson-databind-2.8.8.jar 'https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.8.8/jackson-databind-2.8.8.jar'",
        "probe_cmd": "ls /opt/jars/jackson-databind-2.8.8.jar >/dev/null 2>&1 && echo 'Version: 2.8.8'",
        "fix_cmd": "rm -f /opt/jars/jackson-databind-2.8.8.jar && wget -qO /opt/jars/jackson-databind-2.8.11.1.jar 'https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.8.11.1/jackson-databind-2.8.11.1.jar'",
    },
    "CVE-2019-12384": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "jackson-databind",
        "vulnerable_version": "2.9.9",
        "fixed_version": "2.9.10",
        "maven_coord": "com.fasterxml.jackson.core:jackson-databind",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/jackson-databind-2.9.9.jar 'https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.9.9/jackson-databind-2.9.9.jar'",
        "probe_cmd": "ls /opt/jars/jackson-databind-2.9.9.jar >/dev/null 2>&1 && echo 'Version: 2.9.9'",
        "fix_cmd": "rm -f /opt/jars/jackson-databind-2.9.9.jar && wget -qO /opt/jars/jackson-databind-2.9.10.jar 'https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.9.10/jackson-databind-2.9.10.jar'",
    },
    "CVE-2022-1471": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "snakeyaml",
        "vulnerable_version": "1.33",
        "fixed_version": "2.0",
        "maven_coord": "org.yaml:snakeyaml",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/snakeyaml-1.33.jar 'https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.33/snakeyaml-1.33.jar'",
        "probe_cmd": "ls /opt/jars/snakeyaml-1.33.jar >/dev/null 2>&1 && echo 'Version: 1.33'",
        "fix_cmd": "rm -f /opt/jars/snakeyaml-1.33.jar && wget -qO /opt/jars/snakeyaml-2.0.jar 'https://repo1.maven.org/maven2/org/yaml/snakeyaml/2.0/snakeyaml-2.0.jar'",
    },
    "CVE-2022-42889": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "commons-text",
        "vulnerable_version": "1.9",
        "fixed_version": "1.10.0",
        "maven_coord": "org.apache.commons:commons-text",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/commons-text-1.9.jar 'https://repo1.maven.org/maven2/org/apache/commons/commons-text/1.9/commons-text-1.9.jar'",
        "probe_cmd": "ls /opt/jars/commons-text-1.9.jar >/dev/null 2>&1 && echo 'Version: 1.9'",
        "fix_cmd": "rm -f /opt/jars/commons-text-1.9.jar && wget -qO /opt/jars/commons-text-1.10.0.jar 'https://repo1.maven.org/maven2/org/apache/commons/commons-text/1.10.0/commons-text-1.10.0.jar'",
    },
    "CVE-2022-36033": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "jsoup",
        "vulnerable_version": "1.15.2",
        "fixed_version": "1.15.3",
        "maven_coord": "org.jsoup:jsoup",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/jsoup-1.15.2.jar 'https://repo1.maven.org/maven2/org/jsoup/jsoup/1.15.2/jsoup-1.15.2.jar'",
        "probe_cmd": "ls /opt/jars/jsoup-1.15.2.jar >/dev/null 2>&1 && echo 'Version: 1.15.2'",
        "fix_cmd": "rm -f /opt/jars/jsoup-1.15.2.jar && wget -qO /opt/jars/jsoup-1.15.3.jar 'https://repo1.maven.org/maven2/org/jsoup/jsoup/1.15.3/jsoup-1.15.3.jar'",
    },
    "CVE-2022-25647": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "gson",
        "vulnerable_version": "2.8.8",
        "fixed_version": "2.8.9",
        "maven_coord": "com.google.code.gson:gson",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/gson-2.8.8.jar 'https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar'",
        "probe_cmd": "ls /opt/jars/gson-2.8.8.jar >/dev/null 2>&1 && echo 'Version: 2.8.8'",
        "fix_cmd": "rm -f /opt/jars/gson-2.8.8.jar && wget -qO /opt/jars/gson-2.8.9.jar 'https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar'",
    },
    "CVE-2022-1259": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "undertow-core",
        "vulnerable_version": "2.2.16.Final",
        "fixed_version": "2.2.17.Final",
        "maven_coord": "io.undertow:undertow-core",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/undertow-core-2.2.16.Final.jar 'https://repo1.maven.org/maven2/io/undertow/undertow-core/2.2.16.Final/undertow-core-2.2.16.Final.jar'",
        "probe_cmd": "ls /opt/jars/undertow-core-2.2.16.Final.jar >/dev/null 2>&1 && echo 'Version: 2.2.16.Final'",
        "fix_cmd": "rm -f /opt/jars/undertow-core-2.2.16.Final.jar && wget -qO /opt/jars/undertow-core-2.2.17.Final.jar 'https://repo1.maven.org/maven2/io/undertow/undertow-core/2.2.17.Final/undertow-core-2.2.17.Final.jar'",
    },
    "CVE-2022-31197": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "postgresql",
        "vulnerable_version": "42.4.0",
        "fixed_version": "42.4.1",
        "maven_coord": "org.postgresql:postgresql",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/postgresql-42.4.0.jar 'https://repo1.maven.org/maven2/org/postgresql/postgresql/42.4.0/postgresql-42.4.0.jar'",
        "probe_cmd": "ls /opt/jars/postgresql-42.4.0.jar >/dev/null 2>&1 && echo 'Version: 42.4.0'",
        "fix_cmd": "rm -f /opt/jars/postgresql-42.4.0.jar && wget -qO /opt/jars/postgresql-42.4.1.jar 'https://repo1.maven.org/maven2/org/postgresql/postgresql/42.4.1/postgresql-42.4.1.jar'",
    },
    "CVE-2021-22569": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "protobuf-java",
        "vulnerable_version": "3.19.1",
        "fixed_version": "3.19.2",
        "maven_coord": "com.google.protobuf:protobuf-java",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/protobuf-java-3.19.1.jar 'https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.19.1/protobuf-java-3.19.1.jar'",
        "probe_cmd": "ls /opt/jars/protobuf-java-3.19.1.jar >/dev/null 2>&1 && echo 'Version: 3.19.1'",
        "fix_cmd": "rm -f /opt/jars/protobuf-java-3.19.1.jar && wget -qO /opt/jars/protobuf-java-3.19.2.jar 'https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.19.2/protobuf-java-3.19.2.jar'",
    },
    "CVE-2023-46604": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "activemq-broker",
        "vulnerable_version": "5.17.3",
        "fixed_version": "5.18.3",
        "maven_coord": "org.apache.activemq:activemq-broker",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/activemq-broker-5.17.3.jar 'https://repo1.maven.org/maven2/org/apache/activemq/activemq-broker/5.17.3/activemq-broker-5.17.3.jar'",
        "probe_cmd": "ls /opt/jars/activemq-broker-5.17.3.jar >/dev/null 2>&1 && echo 'Version: 5.17.3'",
        "fix_cmd": "rm -f /opt/jars/activemq-broker-5.17.3.jar && wget -qO /opt/jars/activemq-broker-5.18.3.jar 'https://repo1.maven.org/maven2/org/apache/activemq/activemq-broker/5.18.3/activemq-broker-5.18.3.jar'",
    },
    "CVE-2022-26336": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "poi-ooxml",
        "vulnerable_version": "5.1.0",
        "fixed_version": "5.2.0",
        "maven_coord": "org.apache.poi:poi-ooxml",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/poi-ooxml-5.1.0.jar 'https://repo1.maven.org/maven2/org/apache/poi/poi-ooxml/5.1.0/poi-ooxml-5.1.0.jar'",
        "probe_cmd": "ls /opt/jars/poi-ooxml-5.1.0.jar >/dev/null 2>&1 && echo 'Version: 5.1.0'",
        "fix_cmd": "rm -f /opt/jars/poi-ooxml-5.1.0.jar && wget -qO /opt/jars/poi-ooxml-5.2.0.jar 'https://repo1.maven.org/maven2/org/apache/poi/poi-ooxml/5.2.0/poi-ooxml-5.2.0.jar'",
    },
    # Spring Security (web-framework but still a maven jar)
    "CVE-2022-22978": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "spring-security-web",
        "vulnerable_version": "5.6.3",
        "fixed_version": "5.6.4",
        "maven_coord": "org.springframework.security:spring-security-web",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/spring-security-web-5.6.3.jar 'https://repo1.maven.org/maven2/org/springframework/security/spring-security-web/5.6.3/spring-security-web-5.6.3.jar'",
        "probe_cmd": "ls /opt/jars/spring-security-web-5.6.3.jar >/dev/null 2>&1 && echo 'Version: 5.6.3'",
        "fix_cmd": "rm -f /opt/jars/spring-security-web-5.6.3.jar && wget -qO /opt/jars/spring-security-web-5.6.4.jar 'https://repo1.maven.org/maven2/org/springframework/security/spring-security-web/5.6.4/spring-security-web-5.6.4.jar'",
    },
    # Spring Framework mvcRequestMatcher bypass
    "CVE-2023-20860": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "spring-webmvc",
        "vulnerable_version": "6.0.6",
        "fixed_version": "6.0.7",
        "maven_coord": "org.springframework:spring-webmvc",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/spring-webmvc-6.0.6.jar 'https://repo1.maven.org/maven2/org/springframework/spring-webmvc/6.0.6/spring-webmvc-6.0.6.jar'",
        "probe_cmd": "ls /opt/jars/spring-webmvc-6.0.6.jar >/dev/null 2>&1 && echo 'Version: 6.0.6'",
        "fix_cmd": "rm -f /opt/jars/spring-webmvc-6.0.6.jar && wget -qO /opt/jars/spring-webmvc-6.0.7.jar 'https://repo1.maven.org/maven2/org/springframework/spring-webmvc/6.0.7/spring-webmvc-6.0.7.jar'",
    },
    # Spring Data Commons SpEL RCE
    "CVE-2018-1273": {
        "install_type": "maven_jar",
        "install_channel": "jar",
        "package_name": "spring-data-commons",
        "vulnerable_version": "2.0.5.RELEASE",
        "fixed_version": "2.0.6.RELEASE",
        "maven_coord": "org.springframework.data:spring-data-commons",
        "setup_cmd": "mkdir -p /opt/jars",
        "install_cmd": "wget -qO /opt/jars/spring-data-commons-2.0.5.RELEASE.jar 'https://repo1.maven.org/maven2/org/springframework/data/spring-data-commons/2.0.5.RELEASE/spring-data-commons-2.0.5.RELEASE.jar'",
        "probe_cmd": "ls /opt/jars/spring-data-commons-2.0.5.RELEASE.jar >/dev/null 2>&1 && echo 'Version: 2.0.5.RELEASE'",
        "fix_cmd": "rm -f /opt/jars/spring-data-commons-2.0.5.RELEASE.jar && wget -qO /opt/jars/spring-data-commons-2.0.6.RELEASE.jar 'https://repo1.maven.org/maven2/org/springframework/data/spring-data-commons/2.0.6.RELEASE/spring-data-commons-2.0.6.RELEASE.jar'",
    },

    # ─────────────────────────────────────────────────────────────────────
    # PIP PACKAGE  (install_type=pip_package, install_channel=pip)
    # ─────────────────────────────────────────────────────────────────────
    "CVE-2024-22195": {
        "install_type": "pip_package",
        "install_channel": "pip",
        "package_name": "Jinja2",
        "vulnerable_version": "3.1.2",
        "fixed_version": "3.1.3",
        "setup_cmd": "pip install --quiet pip",
        "install_cmd": "pip install --quiet 'Jinja2==3.1.2'",
        "probe_cmd": "pip show Jinja2 2>/dev/null | grep -i '^version:'",
        "fix_cmd": "pip install --quiet 'Jinja2==3.1.3'",
    },
    "CVE-2021-28957": {
        "install_type": "pip_package",
        "install_channel": "pip",
        "package_name": "lxml",
        "vulnerable_version": "4.6.2",
        "fixed_version": "4.6.3",
        "setup_cmd": "pip install --quiet pip",
        "install_cmd": "pip install --quiet 'lxml==4.6.2'",
        "probe_cmd": "pip show lxml 2>/dev/null | grep -i '^version:'",
        "fix_cmd": "pip install --quiet 'lxml==4.6.3'",
    },
    "CVE-2024-21503": {
        "install_type": "pip_package",
        "install_channel": "pip",
        "package_name": "black",
        "vulnerable_version": "24.2.0",
        "fixed_version": "24.3.0",
        "setup_cmd": "pip install --quiet pip",
        "install_cmd": "pip install --quiet 'black==24.2.0'",
        "probe_cmd": "pip show black 2>/dev/null | grep -i '^version:'",
        "fix_cmd": "pip install --quiet 'black==24.3.0'",
    },

    # ─────────────────────────────────────────────────────────────────────
    # NPM PACKAGE  (install_type=npm_package, install_channel=npm)
    # ─────────────────────────────────────────────────────────────────────
    "CVE-2022-23529": {
        "install_type": "npm_package",
        "install_channel": "npm",
        "package_name": "jsonwebtoken",
        "vulnerable_version": "8.5.1",
        "fixed_version": "9.0.0",
        "setup_cmd": "mkdir -p /opt/npm_pkg && cd /opt/npm_pkg && npm init -y --silent 2>/dev/null",
        "install_cmd": "cd /opt/npm_pkg && npm install --save jsonwebtoken@8.5.1 --silent 2>/dev/null",
        "probe_cmd": "node -e \"console.log('Version: ' + require('/opt/npm_pkg/node_modules/jsonwebtoken/package.json').version)\"",
        "fix_cmd": "cd /opt/npm_pkg && npm install --save jsonwebtoken@9.0.0 --silent 2>/dev/null",
    },
    "CVE-2022-25883": {
        "install_type": "npm_package",
        "install_channel": "npm",
        "package_name": "semver",
        "vulnerable_version": "7.5.1",
        "fixed_version": "7.5.2",
        "setup_cmd": "mkdir -p /opt/npm_pkg && cd /opt/npm_pkg && npm init -y --silent 2>/dev/null",
        "install_cmd": "cd /opt/npm_pkg && npm install --save semver@7.5.1 --silent 2>/dev/null",
        "probe_cmd": "node -e \"console.log('Version: ' + require('/opt/npm_pkg/node_modules/semver/package.json').version)\"",
        "fix_cmd": "cd /opt/npm_pkg && npm install --save semver@7.5.2 --silent 2>/dev/null",
    },
    "CVE-2023-42282": {
        "install_type": "npm_package",
        "install_channel": "npm",
        "package_name": "ip",
        "vulnerable_version": "2.0.0",
        "fixed_version": "2.0.1",
        "setup_cmd": "mkdir -p /opt/npm_pkg && cd /opt/npm_pkg && npm init -y --silent 2>/dev/null",
        "install_cmd": "cd /opt/npm_pkg && npm install --save ip@2.0.0 --silent 2>/dev/null",
        "probe_cmd": "node -e \"console.log('Version: ' + require('/opt/npm_pkg/node_modules/ip/package.json').version)\"",
        "fix_cmd": "cd /opt/npm_pkg && npm install --save ip@2.0.1 --silent 2>/dev/null",
    },
    "CVE-2020-11023": {
        "install_type": "npm_package",
        "install_channel": "npm",
        "package_name": "jquery",
        "vulnerable_version": "3.4.1",
        "fixed_version": "3.5.0",
        "setup_cmd": "mkdir -p /opt/npm_pkg && cd /opt/npm_pkg && npm init -y --silent 2>/dev/null",
        "install_cmd": "cd /opt/npm_pkg && npm install --save jquery@3.4.1 --silent 2>/dev/null",
        "probe_cmd": "node -e \"console.log('Version: ' + require('/opt/npm_pkg/node_modules/jquery/package.json').version)\"",
        "fix_cmd": "cd /opt/npm_pkg && npm install --save jquery@3.5.0 --silent 2>/dev/null",
    },

    # ─────────────────────────────────────────────────────────────────────
    # GEM PACKAGE  (install_type=gem_package, install_channel=gem)
    # ─────────────────────────────────────────────────────────────────────
    "CVE-2023-26119": {
        "install_type": "gem_package",
        "install_channel": "gem",
        "package_name": "loofah",
        "vulnerable_version": "2.21.2",
        "fixed_version": "2.21.3",
        "setup_cmd": "gem install bundler --no-document --silent 2>/dev/null || true",
        "install_cmd": "gem install loofah -v 2.21.2 --no-document",
        "probe_cmd": "gem list loofah --exact 2>/dev/null | head -1",
        "fix_cmd": "gem install loofah -v 2.21.3 --no-document",
    },

    # ─────────────────────────────────────────────────────────────────────
    # COMPOSER / PHP  (install_type=composer_package, install_channel=app)
    # ─────────────────────────────────────────────────────────────────────
    "CVE-2017-9841": {
        "install_type": "composer_package",
        "install_channel": "app",
        "package_name": "phpunit/phpunit",
        "vulnerable_version": "4.8.27",
        "fixed_version": "4.8.28",
        "setup_cmd": "mkdir -p /opt/phpunit && cd /opt/phpunit && (which composer >/dev/null 2>&1 || curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer)",
        "install_cmd": "cd /opt/phpunit && composer require --quiet phpunit/phpunit:4.8.27",
        "probe_cmd": "cd /opt/phpunit && php vendor/phpunit/phpunit/phpunit --version 2>/dev/null | head -1",
        "fix_cmd": "cd /opt/phpunit && composer require --quiet phpunit/phpunit:4.8.28",
    },

    # ─────────────────────────────────────────────────────────────────────
    # SYSTEM PACKAGE  (install_type=system_package, install_channel=apt)
    # ─────────────────────────────────────────────────────────────────────
    "CVE-2024-3094": {
        "install_type": "system_package",
        "install_channel": "apt",
        "package_name": "xz-utils",
        "vulnerable_version": "5.6.0",
        "fixed_version": "5.4.6",
        "setup_cmd": "apt-get update -qq",
        "install_cmd": "mkdir -p /opt/xz && echo '5.6.0' > /opt/xz/VERSION",
        "probe_cmd": "cat /opt/xz/VERSION 2>/dev/null && echo 'Version: 5.6.0'",
        "fix_cmd": "echo '5.4.6' > /opt/xz/VERSION",
    },
    "CVE-2021-3156": {
        "install_type": "system_package",
        "install_channel": "apt",
        "package_name": "sudo",
        "vulnerable_version": "1.9.5p1",
        "fixed_version": "1.9.5p2",
        "setup_cmd": "apt-get update -qq",
        "install_cmd": "mkdir -p /opt/sudo && echo '1.9.5p1' > /opt/sudo/VERSION",
        "probe_cmd": "cat /opt/sudo/VERSION 2>/dev/null && echo 'Version: 1.9.5p1'",
        "fix_cmd": "echo '1.9.5p2' > /opt/sudo/VERSION",
    },
    "CVE-2014-7169": {
        "install_type": "system_package",
        "install_channel": "apt",
        "package_name": "bash",
        "vulnerable_version": "4.3.25",
        "fixed_version": "4.3.30",
        "setup_cmd": "apt-get update -qq",
        "install_cmd": "mkdir -p /opt/bash && echo '4.3.25' > /opt/bash/VERSION",
        "probe_cmd": "cat /opt/bash/VERSION 2>/dev/null && echo 'Version: 4.3.25'",
        "fix_cmd": "echo '4.3.30' > /opt/bash/VERSION",
    },
    "CVE-2019-14287": {
        "install_type": "system_package",
        "install_channel": "apt",
        "package_name": "sudo",
        "vulnerable_version": "1.8.27",
        "fixed_version": "1.8.28",
        "setup_cmd": "apt-get update -qq",
        "install_cmd": "mkdir -p /opt/sudo && echo '1.8.27' > /opt/sudo/VERSION",
        "probe_cmd": "cat /opt/sudo/VERSION 2>/dev/null && echo 'Version: 1.8.27'",
        "fix_cmd": "echo '1.8.28' > /opt/sudo/VERSION",
    },
    "CVE-2022-3602": {
        "install_type": "system_package",
        "install_channel": "apt",
        "package_name": "openssl",
        "vulnerable_version": "3.0.6",
        "fixed_version": "3.0.7",
        "setup_cmd": "apt-get update -qq",
        "install_cmd": "mkdir -p /opt/openssl && echo '3.0.6' > /opt/openssl/VERSION",
        "probe_cmd": "cat /opt/openssl/VERSION 2>/dev/null && echo 'Version: 3.0.6'",
        "fix_cmd": "echo '3.0.7' > /opt/openssl/VERSION",
    },
    "CVE-2022-3786": {
        "install_type": "system_package",
        "install_channel": "apt",
        "package_name": "openssl",
        "vulnerable_version": "3.0.5",
        "fixed_version": "3.0.7",
        "setup_cmd": "apt-get update -qq",
        "install_cmd": "mkdir -p /opt/openssl && echo '3.0.5' > /opt/openssl/VERSION",
        "probe_cmd": "cat /opt/openssl/VERSION 2>/dev/null && echo 'Version: 3.0.5'",
        "fix_cmd": "echo '3.0.7' > /opt/openssl/VERSION",
    },
    "CVE-2023-0286": {
        "install_type": "system_package",
        "install_channel": "apt",
        "package_name": "openssl",
        "vulnerable_version": "3.0.7",
        "fixed_version": "3.0.8",
        "setup_cmd": "apt-get update -qq",
        "install_cmd": "mkdir -p /opt/openssl && echo '3.0.7' > /opt/openssl/VERSION",
        "probe_cmd": "cat /opt/openssl/VERSION 2>/dev/null && echo 'Version: 3.0.7'",
        "fix_cmd": "echo '3.0.8' > /opt/openssl/VERSION",
    },
    "CVE-2022-2068": {
        "install_type": "system_package",
        "install_channel": "apt",
        "package_name": "openssl",
        "vulnerable_version": "3.0.3",
        "fixed_version": "3.0.4",
        "setup_cmd": "apt-get update -qq",
        "install_cmd": "mkdir -p /opt/openssl && echo '3.0.3' > /opt/openssl/VERSION",
        "probe_cmd": "cat /opt/openssl/VERSION 2>/dev/null && echo 'Version: 3.0.3'",
        "fix_cmd": "echo '3.0.4' > /opt/openssl/VERSION",
    },
    "CVE-2024-6387": {
        "install_type": "system_package",
        "install_channel": "apt",
        "package_name": "openssh-server",
        "vulnerable_version": "9.7p1",
        "fixed_version": "9.8p1",
        "setup_cmd": "apt-get update -qq",
        "install_cmd": "mkdir -p /opt/openssh && echo '9.7p1' > /opt/openssh/VERSION",
        "probe_cmd": "cat /opt/openssh/VERSION 2>/dev/null && echo 'Version: 9.7p1'",
        "fix_cmd": "echo '9.8p1' > /opt/openssh/VERSION",
    },
    "CVE-2023-38408": {
        "install_type": "system_package",
        "install_channel": "apt",
        "package_name": "openssh-client",
        "vulnerable_version": "9.3p1",
        "fixed_version": "9.3p2",
        "setup_cmd": "apt-get update -qq",
        "install_cmd": "mkdir -p /opt/openssh && echo '9.3p1' > /opt/openssh/VERSION",
        "probe_cmd": "cat /opt/openssh/VERSION 2>/dev/null && echo 'Version: 9.3p1'",
        "fix_cmd": "echo '9.3p2' > /opt/openssh/VERSION",
    },
    "CVE-2019-10149": {
        "install_type": "system_package",
        "install_channel": "apt",
        "package_name": "exim4",
        "vulnerable_version": "4.91",
        "fixed_version": "4.92",
        "setup_cmd": "apt-get update -qq",
        "install_cmd": "mkdir -p /opt/exim && echo '4.91' > /opt/exim/VERSION",
        "probe_cmd": "cat /opt/exim/VERSION 2>/dev/null && echo 'Version: 4.91'",
        "fix_cmd": "echo '4.92' > /opt/exim/VERSION",
    },
    "CVE-2020-28018": {
        "install_type": "system_package",
        "install_channel": "apt",
        "package_name": "exim4",
        "vulnerable_version": "4.94",
        "fixed_version": "4.94.2",
        "setup_cmd": "apt-get update -qq",
        "install_cmd": "mkdir -p /opt/exim && echo '4.94' > /opt/exim/VERSION",
        "probe_cmd": "cat /opt/exim/VERSION 2>/dev/null && echo 'Version: 4.94'",
        "fix_cmd": "echo '4.94.2' > /opt/exim/VERSION",
    },
    "CVE-2016-2776": {
        "install_type": "system_package",
        "install_channel": "apt",
        "package_name": "bind9",
        "vulnerable_version": "9.10.4-P2",
        "fixed_version": "9.10.4-P3",
        "setup_cmd": "apt-get update -qq",
        "install_cmd": "mkdir -p /opt/bind && echo '9.10.4-P2' > /opt/bind/VERSION",
        "probe_cmd": "cat /opt/bind/VERSION 2>/dev/null && echo 'Version: 9.10.4-P2'",
        "fix_cmd": "echo '9.10.4-P3' > /opt/bind/VERSION",
    },
    # httpd as system package (host-class CVEs)
    "CVE-2022-22720": {
        "install_type": "system_package",
        "install_channel": "apt",
        "package_name": "apache2",
        "vulnerable_version": "2.4.52",
        "fixed_version": "2.4.53",
        "setup_cmd": "apt-get update -qq",
        "install_cmd": "mkdir -p /opt/httpd && echo '2.4.52' > /opt/httpd/VERSION",
        "probe_cmd": "cat /opt/httpd/VERSION 2>/dev/null && echo 'Version: 2.4.52'",
        "fix_cmd": "echo '2.4.53' > /opt/httpd/VERSION",
    },
    "CVE-2022-23943": {
        "install_type": "system_package",
        "install_channel": "apt",
        "package_name": "apache2",
        "vulnerable_version": "2.4.52",
        "fixed_version": "2.4.53",
        "setup_cmd": "apt-get update -qq",
        "install_cmd": "mkdir -p /opt/httpd && echo '2.4.52' > /opt/httpd/VERSION",
        "probe_cmd": "cat /opt/httpd/VERSION 2>/dev/null && echo 'Version: 2.4.52'",
        "fix_cmd": "echo '2.4.53' > /opt/httpd/VERSION",
    },
    "CVE-2023-25690": {
        "install_type": "system_package",
        "install_channel": "apt",
        "package_name": "apache2",
        "vulnerable_version": "2.4.55",
        "fixed_version": "2.4.56",
        "setup_cmd": "apt-get update -qq",
        "install_cmd": "mkdir -p /opt/httpd && echo '2.4.55' > /opt/httpd/VERSION",
        "probe_cmd": "cat /opt/httpd/VERSION 2>/dev/null && echo 'Version: 2.4.55'",
        "fix_cmd": "echo '2.4.56' > /opt/httpd/VERSION",
    },

    # ─────────────────────────────────────────────────────────────────────
    # BINARY DOWNLOAD  (install_type=binary_download, install_channel=binary)
    # ─────────────────────────────────────────────────────────────────────
    "CVE-2019-5736": {
        "install_type": "binary_download",
        "install_channel": "binary",
        "package_name": "runc",
        "vulnerable_version": "1.0.0-rc6",
        "fixed_version": "1.0.0-rc7",
        "binary_url": "https://github.com/opencontainers/runc/releases/download/v1.0.0-rc6/runc.amd64",
        "setup_cmd": "mkdir -p /opt/bin",
        "install_cmd": "wget -qO /opt/bin/runc 'https://github.com/opencontainers/runc/releases/download/v1.0.0-rc6/runc.amd64' && chmod +x /opt/bin/runc",
        "probe_cmd": "/opt/bin/runc --version 2>/dev/null | head -1",
        "fix_cmd": "wget -qO /opt/bin/runc 'https://github.com/opencontainers/runc/releases/download/v1.0.0-rc7/runc.amd64' && chmod +x /opt/bin/runc",
    },
    "CVE-2024-21626": {
        "install_type": "binary_download",
        "install_channel": "binary",
        "package_name": "runc",
        "vulnerable_version": "1.1.11",
        "fixed_version": "1.1.12",
        "binary_url": "https://github.com/opencontainers/runc/releases/download/v1.1.11/runc.amd64",
        "setup_cmd": "mkdir -p /opt/bin",
        "install_cmd": "wget -qO /opt/bin/runc 'https://github.com/opencontainers/runc/releases/download/v1.1.11/runc.amd64' && chmod +x /opt/bin/runc",
        "probe_cmd": "/opt/bin/runc --version 2>/dev/null | head -1",
        "fix_cmd": "wget -qO /opt/bin/runc 'https://github.com/opencontainers/runc/releases/download/v1.1.12/runc.amd64' && chmod +x /opt/bin/runc",
    },
    "CVE-2021-30465": {
        "install_type": "binary_download",
        "install_channel": "binary",
        "package_name": "runc",
        "vulnerable_version": "1.0.0-rc94",
        "fixed_version": "1.0.0-rc95",
        "binary_url": "https://github.com/opencontainers/runc/releases/download/v1.0.0-rc94/runc.amd64",
        "setup_cmd": "mkdir -p /opt/bin",
        "install_cmd": "wget -qO /opt/bin/runc 'https://github.com/opencontainers/runc/releases/download/v1.0.0-rc94/runc.amd64' && chmod +x /opt/bin/runc",
        "probe_cmd": "/opt/bin/runc --version 2>/dev/null | head -1",
        "fix_cmd": "wget -qO /opt/bin/runc 'https://github.com/opencontainers/runc/releases/download/v1.0.0-rc95/runc.amd64' && chmod +x /opt/bin/runc",
    },
    "CVE-2022-29162": {
        "install_type": "binary_download",
        "install_channel": "binary",
        "package_name": "runc",
        "vulnerable_version": "1.1.1",
        "fixed_version": "1.1.2",
        "binary_url": "https://github.com/opencontainers/runc/releases/download/v1.1.1/runc.amd64",
        "setup_cmd": "mkdir -p /opt/bin",
        "install_cmd": "wget -qO /opt/bin/runc 'https://github.com/opencontainers/runc/releases/download/v1.1.1/runc.amd64' && chmod +x /opt/bin/runc",
        "probe_cmd": "/opt/bin/runc --version 2>/dev/null | head -1",
        "fix_cmd": "wget -qO /opt/bin/runc 'https://github.com/opencontainers/runc/releases/download/v1.1.2/runc.amd64' && chmod +x /opt/bin/runc",
    },
    "CVE-2022-23648": {
        "install_type": "binary_download",
        "install_channel": "binary",
        "package_name": "containerd",
        "vulnerable_version": "1.6.0",
        "fixed_version": "1.6.1",
        "binary_url": "https://github.com/containerd/containerd/releases/download/v1.6.0/containerd-1.6.0-linux-amd64.tar.gz",
        "setup_cmd": "mkdir -p /opt/containerd",
        "install_cmd": "wget -qO- 'https://github.com/containerd/containerd/releases/download/v1.6.0/containerd-1.6.0-linux-amd64.tar.gz' | tar -xzf - -C /opt/containerd",
        "probe_cmd": "/opt/containerd/bin/containerd --version 2>/dev/null | head -1",
        "fix_cmd": "rm -rf /opt/containerd/bin && wget -qO- 'https://github.com/containerd/containerd/releases/download/v1.6.1/containerd-1.6.1-linux-amd64.tar.gz' | tar -xzf - -C /opt/containerd",
    },
    "CVE-2023-25153": {
        "install_type": "binary_download",
        "install_channel": "binary",
        "package_name": "buildkit",
        "vulnerable_version": "0.10.4",
        "fixed_version": "0.10.5",
        "binary_url": "https://github.com/moby/buildkit/releases/download/v0.10.4/buildkit-v0.10.4.linux-amd64.tar.gz",
        "setup_cmd": "mkdir -p /opt/buildkit",
        "install_cmd": "wget -qO- 'https://github.com/moby/buildkit/releases/download/v0.10.4/buildkit-v0.10.4.linux-amd64.tar.gz' | tar -xzf - -C /opt/buildkit",
        "probe_cmd": "/opt/buildkit/bin/buildkitd --version 2>/dev/null | head -1",
        "fix_cmd": "rm -rf /opt/buildkit/bin && wget -qO- 'https://github.com/moby/buildkit/releases/download/v0.10.5/buildkit-v0.10.5.linux-amd64.tar.gz' | tar -xzf - -C /opt/buildkit",
    },
    "CVE-2021-25741": {
        "install_type": "binary_download",
        "install_channel": "binary",
        "package_name": "kubelet",
        "vulnerable_version": "1.22.1",
        "fixed_version": "1.22.2",
        "binary_url": "https://dl.k8s.io/v1.22.1/bin/linux/amd64/kubelet",
        "setup_cmd": "mkdir -p /opt/bin",
        "install_cmd": "wget -qO /opt/bin/kubelet 'https://dl.k8s.io/v1.22.1/bin/linux/amd64/kubelet' && chmod +x /opt/bin/kubelet",
        "probe_cmd": "/opt/bin/kubelet --version 2>/dev/null",
        "fix_cmd": "wget -qO /opt/bin/kubelet 'https://dl.k8s.io/v1.22.2/bin/linux/amd64/kubelet' && chmod +x /opt/bin/kubelet",
    },
    "CVE-2018-1002105": {
        "install_type": "binary_download",
        "install_channel": "binary",
        "package_name": "kube-apiserver",
        "vulnerable_version": "1.12.2",
        "fixed_version": "1.13.0",
        "binary_url": "https://dl.k8s.io/v1.12.2/bin/linux/amd64/kube-apiserver",
        "setup_cmd": "mkdir -p /opt/bin",
        "install_cmd": "wget -qO /opt/bin/kube-apiserver 'https://dl.k8s.io/v1.12.2/bin/linux/amd64/kube-apiserver' && chmod +x /opt/bin/kube-apiserver",
        "probe_cmd": "/opt/bin/kube-apiserver --version 2>/dev/null",
        "fix_cmd": "wget -qO /opt/bin/kube-apiserver 'https://dl.k8s.io/v1.13.0/bin/linux/amd64/kube-apiserver' && chmod +x /opt/bin/kube-apiserver",
    },
    "CVE-2022-30635": {
        "install_type": "binary_download",
        "install_channel": "binary",
        "package_name": "go",
        "vulnerable_version": "1.17.12",
        "fixed_version": "1.17.13",
        "binary_url": "https://go.dev/dl/go1.17.12.linux-amd64.tar.gz",
        "setup_cmd": "mkdir -p /opt",
        "install_cmd": "wget -qO- 'https://go.dev/dl/go1.17.12.linux-amd64.tar.gz' | tar -xzf - -C /opt",
        "probe_cmd": "/opt/go/bin/go version 2>/dev/null",
        "fix_cmd": "rm -rf /opt/go && wget -qO- 'https://go.dev/dl/go1.17.13.linux-amd64.tar.gz' | tar -xzf - -C /opt",
    },

    # ─────────────────────────────────────────────────────────────────────
    # APP BINARY  (install_type=app_binary, install_channel=app)
    # Large apps where downloading the full artifact is impractical —
    # use a VERSION file approach to simulate the install.
    # ─────────────────────────────────────────────────────────────────────
    "CVE-2019-1003029": {
        "install_type": "app_binary",
        "install_channel": "app",
        "package_name": "jenkins-script-security-plugin",
        "vulnerable_version": "1.53",
        "fixed_version": "1.54",
        "app_path": "/opt/apps/jenkins",
        "setup_cmd": "mkdir -p /opt/apps/jenkins/plugins",
        "install_cmd": "echo '1.53' > /opt/apps/jenkins/plugins/script-security-VERSION",
        "probe_cmd": "cat /opt/apps/jenkins/plugins/script-security-VERSION 2>/dev/null",
        "fix_cmd": "echo '1.54' > /opt/apps/jenkins/plugins/script-security-VERSION",
    },
    "CVE-2020-9484": {
        "install_type": "app_binary",
        "install_channel": "app",
        "package_name": "tomcat",
        "vulnerable_version": "9.0.34",
        "fixed_version": "9.0.35",
        "app_path": "/opt/apps/tomcat",
        "setup_cmd": "mkdir -p /opt/apps/tomcat",
        "install_cmd": "echo '9.0.34' > /opt/apps/tomcat/VERSION",
        "probe_cmd": "cat /opt/apps/tomcat/VERSION 2>/dev/null",
        "fix_cmd": "echo '9.0.35' > /opt/apps/tomcat/VERSION",
    },
    "CVE-2023-22518": {
        "install_type": "app_binary",
        "install_channel": "app",
        "package_name": "confluence",
        "vulnerable_version": "8.5.2",
        "fixed_version": "7.19.16",
        "app_path": "/opt/apps/confluence",
        "setup_cmd": "mkdir -p /opt/apps/confluence",
        "install_cmd": "echo '8.5.2' > /opt/apps/confluence/VERSION",
        "probe_cmd": "cat /opt/apps/confluence/VERSION 2>/dev/null",
        "fix_cmd": "echo '7.19.16' > /opt/apps/confluence/VERSION",
    },
    "CVE-2023-7028": {
        "install_type": "app_binary",
        "install_channel": "app",
        "package_name": "gitlab-ce",
        "vulnerable_version": "16.7.1",
        "fixed_version": "16.7.2",
        "app_path": "/opt/apps/gitlab",
        "setup_cmd": "mkdir -p /opt/apps/gitlab",
        "install_cmd": "echo '16.7.1' > /opt/apps/gitlab/VERSION",
        "probe_cmd": "cat /opt/apps/gitlab/VERSION 2>/dev/null",
        "fix_cmd": "echo '16.7.2' > /opt/apps/gitlab/VERSION",
    },
    "CVE-2023-2825": {
        "install_type": "app_binary",
        "install_channel": "app",
        "package_name": "gitlab-ce",
        "vulnerable_version": "16.0.0",
        "fixed_version": "16.0.1",
        "app_path": "/opt/apps/gitlab",
        "setup_cmd": "mkdir -p /opt/apps/gitlab",
        "install_cmd": "echo '16.0.0' > /opt/apps/gitlab/VERSION",
        "probe_cmd": "cat /opt/apps/gitlab/VERSION 2>/dev/null",
        "fix_cmd": "echo '16.0.1' > /opt/apps/gitlab/VERSION",
    },
    "CVE-2022-29464": {
        "install_type": "app_binary",
        "install_channel": "app",
        "package_name": "wso2-identity-server",
        "vulnerable_version": "5.11.0",
        "fixed_version": "vendor-patch",
        "app_path": "/opt/apps/wso2is",
        "setup_cmd": "mkdir -p /opt/apps/wso2is",
        "install_cmd": "echo '5.11.0' > /opt/apps/wso2is/VERSION",
        "probe_cmd": "cat /opt/apps/wso2is/VERSION 2>/dev/null",
        "fix_cmd": "echo 'vendor-patch' > /opt/apps/wso2is/VERSION",
    },
    "CVE-2024-23917": {
        "install_type": "app_binary",
        "install_channel": "app",
        "package_name": "teamcity",
        "vulnerable_version": "2023.11.2",
        "fixed_version": "2023.11.3",
        "app_path": "/opt/apps/teamcity",
        "setup_cmd": "mkdir -p /opt/apps/teamcity",
        "install_cmd": "echo '2023.11.2' > /opt/apps/teamcity/VERSION",
        "probe_cmd": "cat /opt/apps/teamcity/VERSION 2>/dev/null",
        "fix_cmd": "echo '2023.11.3' > /opt/apps/teamcity/VERSION",
    },
    "CVE-2022-24682": {
        "install_type": "app_binary",
        "install_channel": "app",
        "package_name": "zimbra",
        "vulnerable_version": "8.8.15.P29",
        "fixed_version": "8.8.15.P30",
        "app_path": "/opt/apps/zimbra",
        "setup_cmd": "mkdir -p /opt/apps/zimbra",
        "install_cmd": "echo '8.8.15.P29' > /opt/apps/zimbra/VERSION",
        "probe_cmd": "cat /opt/apps/zimbra/VERSION 2>/dev/null",
        "fix_cmd": "echo '8.8.15.P30' > /opt/apps/zimbra/VERSION",
    },
    "CVE-2022-27924": {
        "install_type": "app_binary",
        "install_channel": "app",
        "package_name": "zimbra",
        "vulnerable_version": "9.0.0.P25",
        "fixed_version": "9.0.0.P26",
        "app_path": "/opt/apps/zimbra",
        "setup_cmd": "mkdir -p /opt/apps/zimbra",
        "install_cmd": "echo '9.0.0.P25' > /opt/apps/zimbra/VERSION",
        "probe_cmd": "cat /opt/apps/zimbra/VERSION 2>/dev/null",
        "fix_cmd": "echo '9.0.0.P26' > /opt/apps/zimbra/VERSION",
    },
    "CVE-2022-37042": {
        "install_type": "app_binary",
        "install_channel": "app",
        "package_name": "zimbra",
        "vulnerable_version": "9.0.0.P24",
        "fixed_version": "9.0.0.P25",
        "app_path": "/opt/apps/zimbra",
        "setup_cmd": "mkdir -p /opt/apps/zimbra",
        "install_cmd": "echo '9.0.0.P24' > /opt/apps/zimbra/VERSION",
        "probe_cmd": "cat /opt/apps/zimbra/VERSION 2>/dev/null",
        "fix_cmd": "echo '9.0.0.P25' > /opt/apps/zimbra/VERSION",
    },
    "CVE-2022-21661": {
        "install_type": "app_binary",
        "install_channel": "app",
        "package_name": "wordpress",
        "vulnerable_version": "5.8.2",
        "fixed_version": "5.8.3",
        "app_path": "/opt/apps/wordpress",
        "setup_cmd": "mkdir -p /opt/apps/wordpress",
        "install_cmd": "echo '5.8.2' > /opt/apps/wordpress/VERSION",
        "probe_cmd": "cat /opt/apps/wordpress/VERSION 2>/dev/null",
        "fix_cmd": "echo '5.8.3' > /opt/apps/wordpress/VERSION",
    },
    "CVE-2024-1709": {
        "install_type": "app_binary",
        "install_channel": "app",
        "package_name": "screenconnect",
        "vulnerable_version": "23.9.7",
        "fixed_version": "23.9.8",
        "app_path": "/opt/apps/screenconnect",
        "setup_cmd": "mkdir -p /opt/apps/screenconnect",
        "install_cmd": "echo '23.9.7' > /opt/apps/screenconnect/VERSION",
        "probe_cmd": "cat /opt/apps/screenconnect/VERSION 2>/dev/null",
        "fix_cmd": "echo '23.9.8' > /opt/apps/screenconnect/VERSION",
    },
    "CVE-2023-34362": {
        "install_type": "app_binary",
        "install_channel": "app",
        "package_name": "moveit-transfer",
        "vulnerable_version": "2023.0.0",
        "fixed_version": "2023.0.1",
        "app_path": "/opt/apps/moveit",
        "setup_cmd": "mkdir -p /opt/apps/moveit",
        "install_cmd": "echo '2023.0.0' > /opt/apps/moveit/VERSION",
        "probe_cmd": "cat /opt/apps/moveit/VERSION 2>/dev/null",
        "fix_cmd": "echo '2023.0.1' > /opt/apps/moveit/VERSION",
    },

    # ─────────────────────────────────────────────────────────────────────
    # CONFIG / VENDOR  (install_type=config_vendor, install_channel=app)
    # Vendor appliances that cannot be installed — version-file simulation.
    # ─────────────────────────────────────────────────────────────────────
    "CVE-2024-21887": {
        "install_type": "config_vendor",
        "install_channel": "app",
        "package_name": "ivanti-connect-secure",
        "vulnerable_version": "22.7",
        "fixed_version": "vendor-patch",
        "app_path": "/opt/apps/ivanti",
        "setup_cmd": "mkdir -p /opt/apps/ivanti",
        "install_cmd": "echo '22.7' > /opt/apps/ivanti/VERSION",
        "probe_cmd": "cat /opt/apps/ivanti/VERSION 2>/dev/null",
        "fix_cmd": "echo 'vendor-patch' > /opt/apps/ivanti/VERSION",
    },
    "CVE-2023-46805": {
        "install_type": "config_vendor",
        "install_channel": "app",
        "package_name": "ivanti-connect-secure",
        "vulnerable_version": "22.6",
        "fixed_version": "vendor-patch",
        "app_path": "/opt/apps/ivanti",
        "setup_cmd": "mkdir -p /opt/apps/ivanti",
        "install_cmd": "echo '22.6' > /opt/apps/ivanti/VERSION",
        "probe_cmd": "cat /opt/apps/ivanti/VERSION 2>/dev/null",
        "fix_cmd": "echo 'vendor-patch' > /opt/apps/ivanti/VERSION",
    },
    "CVE-2024-3400": {
        "install_type": "config_vendor",
        "install_channel": "app",
        "package_name": "panos-globalprotect",
        "vulnerable_version": "11.1.0",
        "fixed_version": "vendor-hotfix",
        "app_path": "/opt/apps/panos",
        "setup_cmd": "mkdir -p /opt/apps/panos",
        "install_cmd": "echo '11.1.0' > /opt/apps/panos/VERSION",
        "probe_cmd": "cat /opt/apps/panos/VERSION 2>/dev/null",
        "fix_cmd": "echo 'vendor-hotfix' > /opt/apps/panos/VERSION",
    },
    "CVE-2023-3519": {
        "install_type": "config_vendor",
        "install_channel": "app",
        "package_name": "citrix-netscaler",
        "vulnerable_version": "13.1-49.13",
        "fixed_version": "vendor-patch",
        "app_path": "/opt/apps/netscaler",
        "setup_cmd": "mkdir -p /opt/apps/netscaler",
        "install_cmd": "echo '13.1-49.13' > /opt/apps/netscaler/VERSION",
        "probe_cmd": "cat /opt/apps/netscaler/VERSION 2>/dev/null",
        "fix_cmd": "echo 'vendor-patch' > /opt/apps/netscaler/VERSION",
    },
    "CVE-2022-1388": {
        "install_type": "config_vendor",
        "install_channel": "app",
        "package_name": "f5-bigip",
        "vulnerable_version": "16.1.2",
        "fixed_version": "17.0.0",
        "app_path": "/opt/apps/bigip",
        "setup_cmd": "mkdir -p /opt/apps/bigip",
        "install_cmd": "echo '16.1.2' > /opt/apps/bigip/VERSION",
        "probe_cmd": "cat /opt/apps/bigip/VERSION 2>/dev/null",
        "fix_cmd": "echo '17.0.0' > /opt/apps/bigip/VERSION",
    },
    "CVE-2021-22941": {
        "install_type": "config_vendor",
        "install_channel": "app",
        "package_name": "citrix-sharefile",
        "vulnerable_version": "2021.x",
        "fixed_version": "vendor-hotfix",
        "app_path": "/opt/apps/sharefile",
        "setup_cmd": "mkdir -p /opt/apps/sharefile",
        "install_cmd": "echo '2021.x' > /opt/apps/sharefile/VERSION",
        "probe_cmd": "cat /opt/apps/sharefile/VERSION 2>/dev/null",
        "fix_cmd": "echo 'vendor-hotfix' > /opt/apps/sharefile/VERSION",
    },
    "CVE-2024-24919": {
        "install_type": "config_vendor",
        "install_channel": "app",
        "package_name": "checkpoint-quantum",
        "vulnerable_version": "R81.20",
        "fixed_version": "vendor-hotfix",
        "app_path": "/opt/apps/checkpoint",
        "setup_cmd": "mkdir -p /opt/apps/checkpoint",
        "install_cmd": "echo 'R81.20' > /opt/apps/checkpoint/VERSION",
        "probe_cmd": "cat /opt/apps/checkpoint/VERSION 2>/dev/null",
        "fix_cmd": "echo 'vendor-hotfix' > /opt/apps/checkpoint/VERSION",
    },

    # ─────────────────────────────────────────────────────────────────────
    # NOT APPLICABLE  (install_type=not_applicable)
    # Kernel CVEs, protocol-level, vendor-mitigation-only
    # ─────────────────────────────────────────────────────────────────────
    "CVE-2023-44487": {
        "install_type": "not_applicable",
        "install_channel": "apt",
        "package_name": "http2",
        "vulnerable_version": "protocol-level",
        "fixed_version": "vendor-patch",
        "not_applicable_reason": "HTTP/2 Rapid Reset is a protocol-level DoS; no single package to install. Mitigation is server-config (rate-limit RST_STREAM).",
        "setup_cmd": "true",
        "install_cmd": "echo 'NOT_APPLICABLE: protocol-level CVE'",
        "probe_cmd": "echo 'Version: protocol-level'",
        "fix_cmd": "echo 'FIX: apply vendor h2 patch or config rate limit'",
    },
    "CVE-2016-5195": {
        "install_type": "not_applicable",
        "install_channel": "apt",
        "package_name": "linux-kernel",
        "vulnerable_version": "4.8.2",
        "fixed_version": "4.8.3",
        "not_applicable_reason": "Dirty COW is a kernel vulnerability; cannot install a vulnerable kernel in a container sandbox.",
        "setup_cmd": "true",
        "install_cmd": "echo 'NOT_APPLICABLE: kernel CVE'",
        "probe_cmd": "uname -r",
        "fix_cmd": "echo 'FIX: upgrade kernel to >= 4.8.3'",
    },
    "CVE-2022-0847": {
        "install_type": "not_applicable",
        "install_channel": "apt",
        "package_name": "linux-kernel",
        "vulnerable_version": "5.16.10",
        "fixed_version": "5.16.11",
        "not_applicable_reason": "Dirty Pipe is a kernel vulnerability; cannot install a vulnerable kernel in a container sandbox.",
        "setup_cmd": "true",
        "install_cmd": "echo 'NOT_APPLICABLE: kernel CVE'",
        "probe_cmd": "uname -r",
        "fix_cmd": "echo 'FIX: upgrade kernel to >= 5.16.11'",
    },
    "CVE-2021-22555": {
        "install_type": "not_applicable",
        "install_channel": "apt",
        "package_name": "linux-kernel",
        "vulnerable_version": "5.11",
        "fixed_version": "5.12",
        "not_applicable_reason": "Netfilter heap OOB write is a kernel vulnerability; cannot install a vulnerable kernel in a container sandbox.",
        "setup_cmd": "true",
        "install_cmd": "echo 'NOT_APPLICABLE: kernel CVE'",
        "probe_cmd": "uname -r",
        "fix_cmd": "echo 'FIX: upgrade kernel to >= 5.12'",
    },
    "CVE-2022-0185": {
        "install_type": "not_applicable",
        "install_channel": "apt",
        "package_name": "linux-kernel",
        "vulnerable_version": "5.16.1",
        "fixed_version": "5.16.2",
        "not_applicable_reason": "fs_context heap overflow is a kernel vulnerability; cannot install a vulnerable kernel in a container sandbox.",
        "setup_cmd": "true",
        "install_cmd": "echo 'NOT_APPLICABLE: kernel CVE'",
        "probe_cmd": "uname -r",
        "fix_cmd": "echo 'FIX: upgrade kernel to >= 5.16.2'",
    },
    "CVE-2020-8554": {
        "install_type": "not_applicable",
        "install_channel": "binary",
        "package_name": "kube-apiserver",
        "vulnerable_version": "all",
        "fixed_version": "vendor-mitigation",
        "not_applicable_reason": "Kubernetes ExternalIP MITM has no code fix; mitigation is an admission webhook policy. Cannot be installed as a single binary.",
        "setup_cmd": "true",
        "install_cmd": "echo 'NOT_APPLICABLE: vendor-mitigation-only CVE'",
        "probe_cmd": "echo 'Version: all (design issue)'",
        "fix_cmd": "echo 'FIX: deploy ExternalIP admission webhook'",
    },

    # ─────────────────────────────────────────────────────────────────────
    # NEW 2026 CVES (real apt/pip/npm/gem substrate)
    # ─────────────────────────────────────────────────────────────────────
    "CVE-2026-21441": {
        "install_type": 'pip_package',
        "install_channel": 'pip',
        "package_name": 'urllib3',
        "vulnerable_version": '2.5.0',
        "fixed_version": '2.6.3',
        "setup_cmd": 'python3 -m pip install --upgrade pip --quiet || true',
        "install_cmd": 'python3 -m pip install --force-reinstall --no-deps --quiet urllib3==2.5.0',
        "probe_cmd": 'pip show urllib3 2>/dev/null | grep ^Version: || true',
        "fix_cmd": 'python3 -m pip install --upgrade --no-deps --quiet urllib3==2.6.3',
    },
    "CVE-2026-42309": {
        "install_type": 'pip_package',
        "install_channel": 'pip',
        "package_name": 'pillow',
        "vulnerable_version": '11.2.1',
        "fixed_version": '12.2.0',
        "setup_cmd": 'python3 -m pip install --upgrade pip --quiet || true',
        "install_cmd": 'python3 -m pip install --force-reinstall --no-deps --quiet pillow==11.2.1',
        "probe_cmd": 'pip show pillow 2>/dev/null | grep ^Version: || true',
        "fix_cmd": 'python3 -m pip install --upgrade --no-deps --quiet pillow==12.2.0',
    },
    "CVE-2026-27205": {
        "install_type": 'pip_package',
        "install_channel": 'pip',
        "package_name": 'flask',
        "vulnerable_version": '3.1.2',
        "fixed_version": '3.1.3',
        "setup_cmd": 'python3 -m pip install --upgrade pip --quiet || true',
        "install_cmd": 'python3 -m pip install --force-reinstall --no-deps --quiet flask==3.1.2',
        "probe_cmd": 'pip show flask 2>/dev/null | grep ^Version: || true',
        "fix_cmd": 'python3 -m pip install --upgrade --no-deps --quiet flask==3.1.3',
    },
    "CVE-2026-35536": {
        "install_type": 'pip_package',
        "install_channel": 'pip',
        "package_name": 'tornado',
        "vulnerable_version": '6.5.4',
        "fixed_version": '6.5.5',
        "setup_cmd": 'python3 -m pip install --upgrade pip --quiet || true',
        "install_cmd": 'python3 -m pip install --force-reinstall --no-deps --quiet tornado==6.5.4',
        "probe_cmd": 'pip show tornado 2>/dev/null | grep ^Version: || true',
        "fix_cmd": 'python3 -m pip install --upgrade --no-deps --quiet tornado==6.5.5',
    },
    "CVE-2026-41066": {
        "install_type": 'pip_package',
        "install_channel": 'pip',
        "package_name": 'lxml',
        "vulnerable_version": '6.0.0',
        "fixed_version": '6.1.0',
        "setup_cmd": 'python3 -m pip install --upgrade pip --quiet || true',
        "install_cmd": 'python3 -m pip install --force-reinstall --no-deps --quiet lxml==6.0.0',
        "probe_cmd": 'pip show lxml 2>/dev/null | grep ^Version: || true',
        "fix_cmd": 'python3 -m pip install --upgrade --no-deps --quiet lxml==6.1.0',
    },
    "CVE-2026-42044": {
        "install_type": 'npm_package',
        "install_channel": 'npm',
        "package_name": 'axios',
        "vulnerable_version": '1.15.0',
        "fixed_version": '1.15.2',
        "setup_cmd": 'which npm >/dev/null 2>&1 || true',
        "install_cmd": 'npm install -g --silent --no-audit --no-fund axios@1.15.0',
        "probe_cmd": 'npm list -g axios --depth=0 --json 2>/dev/null | python3 -c "import sys,json;d=json.load(sys.stdin);v=(d.get(\'dependencies\') or {}).get(\'axios\',{}).get(\'version\',\'\');print(f\'Version: {v}\') if v else None" || true',
        "fix_cmd": 'npm install -g --silent --no-audit --no-fund axios@1.15.2',
    },
    "CVE-2026-44705": {
        "install_type": 'npm_package',
        "install_channel": 'npm',
        "package_name": 'tmp',
        "vulnerable_version": '0.2.5',
        "fixed_version": '0.2.6',
        "setup_cmd": 'which npm >/dev/null 2>&1 || true',
        "install_cmd": 'npm install -g --silent --no-audit --no-fund tmp@0.2.5',
        "probe_cmd": 'npm list -g tmp --depth=0 --json 2>/dev/null | python3 -c "import sys,json;d=json.load(sys.stdin);v=(d.get(\'dependencies\') or {}).get(\'tmp\',{}).get(\'version\',\'\');print(f\'Version: {v}\') if v else None" || true',
        "fix_cmd": 'npm install -g --silent --no-audit --no-fund tmp@0.2.6',
    },
    "CVE-2026-45736": {
        "install_type": 'npm_package',
        "install_channel": 'npm',
        "package_name": 'ws',
        "vulnerable_version": '8.20.0',
        "fixed_version": '8.20.1',
        "setup_cmd": 'which npm >/dev/null 2>&1 || true',
        "install_cmd": 'npm install -g --silent --no-audit --no-fund ws@8.20.0',
        "probe_cmd": 'npm list -g ws --depth=0 --json 2>/dev/null | python3 -c "import sys,json;d=json.load(sys.stdin);v=(d.get(\'dependencies\') or {}).get(\'ws\',{}).get(\'version\',\'\');print(f\'Version: {v}\') if v else None" || true',
        "fix_cmd": 'npm install -g --silent --no-audit --no-fund ws@8.20.1',
    },
    "CVE-2026-23745": {
        "install_type": 'npm_package',
        "install_channel": 'npm',
        "package_name": 'tar',
        "vulnerable_version": '7.5.2',
        "fixed_version": '7.5.3',
        "setup_cmd": 'which npm >/dev/null 2>&1 || true',
        "install_cmd": 'npm install -g --silent --no-audit --no-fund tar@7.5.2',
        "probe_cmd": 'npm list -g tar --depth=0 --json 2>/dev/null | python3 -c "import sys,json;d=json.load(sys.stdin);v=(d.get(\'dependencies\') or {}).get(\'tar\',{}).get(\'version\',\'\');print(f\'Version: {v}\') if v else None" || true',
        "fix_cmd": 'npm install -g --silent --no-audit --no-fund tar@7.5.3',
    },
    "CVE-2026-2950": {
        "install_type": 'npm_package',
        "install_channel": 'npm',
        "package_name": 'lodash',
        "vulnerable_version": '4.17.21',
        "fixed_version": '4.18.0',
        "setup_cmd": 'which npm >/dev/null 2>&1 || true',
        "install_cmd": 'npm install -g --silent --no-audit --no-fund lodash@4.17.21',
        "probe_cmd": 'npm list -g lodash --depth=0 --json 2>/dev/null | python3 -c "import sys,json;d=json.load(sys.stdin);v=(d.get(\'dependencies\') or {}).get(\'lodash\',{}).get(\'version\',\'\');print(f\'Version: {v}\') if v else None" || true',
        "fix_cmd": 'npm install -g --silent --no-audit --no-fund lodash@4.18.0',
    },
    "CVE-2026-35611": {
        "install_type": 'gem_package',
        "install_channel": 'gem',
        "package_name": 'addressable',
        "vulnerable_version": '2.8.7',
        "fixed_version": '2.9.0',
        "setup_cmd": 'which gem >/dev/null 2>&1 || true',
        "install_cmd": 'gem install addressable -v 2.8.7 --no-document --silent',
        "probe_cmd": "gem list addressable --local 2>/dev/null | grep -i 'addressable' | sed 's/.*(/Version: /;s/)//' || true",
        "fix_cmd": 'gem install addressable -v 2.9.0 --no-document --silent',
    },
    "CVE-2026-34830": {
        "install_type": 'gem_package',
        "install_channel": 'gem',
        "package_name": 'rack',
        "vulnerable_version": '2.2.22',
        "fixed_version": '2.2.23',
        "setup_cmd": 'which gem >/dev/null 2>&1 || true',
        "install_cmd": 'gem install rack -v 2.2.22 --no-document',
        "probe_cmd": "gem list rack --local 2>/dev/null | grep -i 'rack' | sed 's/.*(/Version: /;s/)//' || true",
        "fix_cmd": 'gem install rack -v 2.2.23 --no-document',
    },
    "CVE-2026-26962": {
        "install_type": 'gem_package',
        "install_channel": 'gem',
        "package_name": 'rack',
        "vulnerable_version": '3.2.5',
        "fixed_version": '3.2.6',
        "setup_cmd": 'which gem >/dev/null 2>&1 || true',
        "install_cmd": 'gem install rack -v 3.2.5 --no-document --silent',
        "probe_cmd": "gem list rack --local 2>/dev/null | grep -i 'rack' | sed 's/.*(/Version: /;s/)//' || true",
        "fix_cmd": 'gem install rack -v 3.2.6 --no-document --silent',
    },
    "CVE-2026-26961": {
        "install_type": 'gem_package',
        "install_channel": 'gem',
        "package_name": 'rack',
        "vulnerable_version": '2.2.21',
        "fixed_version": '2.2.23',
        "setup_cmd": 'which gem >/dev/null 2>&1 || true',
        "install_cmd": 'gem install rack -v 2.2.21 --no-document',
        "probe_cmd": "gem list rack --local 2>/dev/null | grep -i 'rack' | sed 's/.*(/Version: /;s/)//' || true",
        "fix_cmd": 'gem install rack -v 2.2.23 --no-document',
    },
    "CVE-2026-25500": {
        "install_type": 'gem_package',
        "install_channel": 'gem',
        "package_name": 'rack',
        "vulnerable_version": '2.2.20',
        "fixed_version": '2.2.22',
        "setup_cmd": 'which gem >/dev/null 2>&1 || true',
        "install_cmd": 'gem install rack -v 2.2.20 --no-document',
        "probe_cmd": "gem list rack --local 2>/dev/null | grep -i 'rack' | sed 's/.*(/Version: /;s/)//' || true",
        "fix_cmd": 'gem install rack -v 2.2.22 --no-document',
    },
    "CVE-2026-47784": {
        "install_type": 'system_package',
        "install_channel": 'apt',
        "package_name": 'memcached',
        "vulnerable_version": '1.6.14-1ubuntu0.1',
        "fixed_version": '1.6.14-1ubuntu0.2',
        "setup_cmd": 'apt-get update -qq',
        "install_cmd": 'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends memcached',
        "probe_cmd": 'dpkg -s memcached 2>/dev/null | grep ^Version: || true',
        "fix_cmd": 'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --only-upgrade memcached',
    },
    "CVE-2026-42945": {
        "install_type": 'system_package',
        "install_channel": 'apt',
        "package_name": 'nginx',
        "vulnerable_version": '1.18.0-6ubuntu14.10',
        "fixed_version": '1.18.0-6ubuntu14.11',
        "setup_cmd": 'apt-get update -qq',
        "install_cmd": 'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends nginx',
        "probe_cmd": 'dpkg -s nginx 2>/dev/null | grep ^Version: || true',
        "fix_cmd": 'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --only-upgrade nginx',
    },
    "CVE-2026-6475": {
        "install_type": 'system_package',
        "install_channel": 'apt',
        "package_name": 'postgresql-14',
        "vulnerable_version": '14.22-0ubuntu0.22.04.1',
        "fixed_version": '14.23-0ubuntu0.22.04.1',
        "setup_cmd": 'apt-get update -qq',
        "install_cmd": 'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends postgresql-14',
        "probe_cmd": 'dpkg -s postgresql-14 2>/dev/null | grep ^Version: || true',
        "fix_cmd": 'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --only-upgrade postgresql-14',
    },
    "CVE-2026-4892": {
        "install_type": 'system_package',
        "install_channel": 'apt',
        "package_name": 'dnsmasq',
        "vulnerable_version": '2.90-0ubuntu0.22.04.2',
        "fixed_version": '2.90-0ubuntu0.22.04.3',
        "setup_cmd": 'apt-get update -qq',
        "install_cmd": 'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends dnsmasq',
        "probe_cmd": 'dpkg -s dnsmasq 2>/dev/null | grep ^Version: || true',
        "fix_cmd": 'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --only-upgrade dnsmasq',
    },
}

# ---------------------------------------------------------------------------
# Validation: ensure all 100 CVEs from the fixture are present
# ---------------------------------------------------------------------------
_EXPECTED_COUNT = 100


def _validate() -> None:
    """Self-check on import: confirm map has exactly 100 entries."""
    actual = len(_INSTALL_MAP)
    if actual != _EXPECTED_COUNT:
        raise RuntimeError(
            f"_INSTALL_MAP has {actual} entries, expected {_EXPECTED_COUNT}. "
            f"Missing or extra entries detected."
        )
    # Verify required keys
    _REQUIRED = {"install_type", "install_channel", "package_name",
                 "vulnerable_version", "fixed_version",
                 "setup_cmd", "install_cmd", "probe_cmd", "fix_cmd"}
    for cve_id, entry in _INSTALL_MAP.items():
        missing = _REQUIRED - set(entry.keys())
        if missing:
            raise RuntimeError(
                f"_INSTALL_MAP[{cve_id!r}] missing keys: {missing}"
            )


_validate()
